import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  bodyHtmlRoot: {
    height: '100%',
    margin: 0,
    fontFamily: 'Arial, sans-serif',
  },
  navbar: {
    flexDirection: 'column',
    justifyContent: 'space-between',
    position: 'absolute', // Use 'absolute' for a fixed position effect
    height: '100%',
    width: 120,
    backgroundColor: 'black',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    padding: 20,
  },
  navLinks: {
    flexDirection: 'column',
  },
  navLink: {
    textDecorationLine: 'none',
    color: 'white',
    paddingVertical: 10,
    marginVertical: 5,
    fontSize: 16,
  },
  navLinkHover: {
    backgroundColor: '#0056b3',
    borderRadius: 4,
    transform: [{ translateY: -5 }],
  },
  profile: {
    position: 'relative',
    textAlign: 'left',
  },
  profileDetails: {
    flexDirection: 'row',
  },
  profileImage: {
    width: 35,
    borderRadius: 20,
    marginTop: 10,
    cursor: 'pointer',
  },
  tooltip: {
    position: 'absolute',
    bottom: 60,
    left: '50%',
    transform: [{ translateX: -50 }],
    width: 120,
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 4,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    padding: 10,
    zIndex: 1000,
  },
  tooltipText: {
    marginVertical: 5,
  },
  tooltipLink: {
    color: '#0056b3',
    textDecorationLine: 'none',
  },
  tooltipLinkHover: {
    textDecorationLine: 'underline',
  },
  content: {
    marginLeft: 170,
    padding: 20,
  },
  section: {
    width: '100%',
    maxWidth: 800,
    marginBottom: 20,
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 8,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionHeader: {
    marginBottom: 10,
    color: 'black',
    fontSize: 18,
    fontWeight: 'bold',
  },
  buttons: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 10,
  },
  button: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 5,
    backgroundColor: 'black',
    color: '#fff',
    textAlign: 'center',
  },
  buttonHover: {
    backgroundColor: '#0056b3',
    transform: [{ translateY: -5 }],
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  textarea: {
    width: '100%',
    padding: 10,
    borderRadius: 5,
    borderColor: '#ced4da',
    borderWidth: 1,
    textAlignVertical: 'top',
    minHeight: 60,
  },
  commentSection: {
    marginTop: 20,
    display: 'none', // React Native doesn't support 'display: none'
  },
  commentSectionHeader: {
    marginBottom: 10,
    color: 'black',
    fontSize: 18,
    fontWeight: 'bold',
  },
  comment: {
    backgroundColor: '#f8f9fa',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
  },
  iconButton: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    fontSize: 24,
    color: 'black',
  },
  iconButtonHover: {
    color: '#0056b3',
  },
  loginContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    width: 300,
    textAlign: 'center',
  },
  loginHeader: {
    marginBottom: 20,
    color: '#333',
    fontSize: 20,
    fontWeight: 'bold',
  },
  loginInput: {
    width: '100%',
    padding: 10,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: '#ced4da',
    borderRadius: 5,
  },
  loginButton: {
    width: '100%',
    padding: 10,
    borderRadius: 5,
    backgroundColor: 'black',
    color: '#fff',
    textAlign: 'center',
  },
  loginButtonHover: {
    backgroundColor: '#0056b3',
  },
  userList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  userCard: {
    backgroundColor: '#f9f9f9',
    padding: 15,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    textAlign: 'center',
    marginBottom: 20,
    width: '45%',
  },
  username: {
    margin: 0,
    fontSize: 24,
    color: 'black',
    fontWeight: 'bold',
  },
  programme: {
    fontSize: 16,
    color: '#555',
  },
  searchBox: {
    position: 'absolute',
    top: 20,
    right: 20,
    marginBottom: 20,
  },
  searchInput: {
    padding: 10,
    width: 250,
    borderRadius: 5,
    borderColor: '#ccc',
    borderWidth: 1,
    fontSize: 16,
  },
  questionItem: {
    marginBottom: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    backgroundColor: '#f9f9f9',
  },
  commentTextarea: {
    width: '100%',
    padding: 10,
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    textAlignVertical: 'top',
    minHeight: 60,
  },
  submitComment: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: 'black',
    color: 'white',
    borderRadius: 5,
    textAlign: 'center',
  },
  submitCommentHover: {
    backgroundColor: '#0056b3',
  },
  active: {
    backgroundColor: '#0056b3',
    color: 'white',
    display: 'inline-block',
  },
});

export default styles;
